// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDC8Rhio_tM0OoyfbJBmmJocBoE0X5cASk',
    appId: '1:1077606986142:web:43f1d40743cd962497268f',
    messagingSenderId: '1077606986142',
    projectId: 'flutter-auction-app',
    authDomain: 'flutter-auction-app.firebaseapp.com',
    storageBucket: 'flutter-auction-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBODaH0dTW2OkihCyhLZq7ih_yyxbkDbi8',
    appId: '1:1077606986142:android:087a9c831fa6b15e97268f',
    messagingSenderId: '1077606986142',
    projectId: 'flutter-auction-app',
    storageBucket: 'flutter-auction-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEV3mcetxXmsKJJFsdYKYek5CfD5Gtnnw',
    appId: '1:1077606986142:ios:b7fe09f4032f970d97268f',
    messagingSenderId: '1077606986142',
    projectId: 'flutter-auction-app',
    storageBucket: 'flutter-auction-app.appspot.com',
    iosBundleId: 'com.example.auctionapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEV3mcetxXmsKJJFsdYKYek5CfD5Gtnnw',
    appId: '1:1077606986142:ios:b7fe09f4032f970d97268f',
    messagingSenderId: '1077606986142',
    projectId: 'flutter-auction-app',
    storageBucket: 'flutter-auction-app.appspot.com',
    iosBundleId: 'com.example.auctionapp',
  );
}
